import React from "react";
import { Box, Typography, Container, Grid } from "@mui/material";
import Page from "./Page";

const About = () => {
  return (
    <Page title="About">
      <Box
        sx={{
          backgroundImage:
            "url(https://cdn.babamail.co.il/Images/2019/8/29/5763a3a0-02eb-4450-80f8-5a1f4626019e.jpg)",
          backgroundPosition: "center",
          backgroundSize: "cover",
          minHeight: "80vh",
          display: "flex",
          alignItems: "center",
          borderRadius: "0.5rem",
        }}
      >
        <Grid container spacing={3}>
          <Grid item xs={12} sm={8} md={9}>
            <Container
              maxWidth="lg"
              sx={{
                width: '50%',
                margin: 0,
                backgroundColor: "rgba(0, 0, 0, 0.5)",
                // padding: "4rem",
                borderRadius: "1rem",
              }}
            >
              <Typography variant="h5" sx={{ py: 4, color: "#fff" ,textAlign:"center" }}>
                Astronomical DashBoard App
              </Typography>
              <Typography
                variant="body1"
                sx={{
                  // width: '50%',
                  color: "#fff",
                  padding: "1rem",
                }}
              >
                Welcome to our React-based dashboard for real-time monitoring of
                astronomical events and sun behavior analysis! Our microservices
                architecture is designed to help you gain valuable insights into
                the physical signals generated by astronomical events, allowing
                you to optimize your knowledge of the cosmos and make better
                predictions for the future. Our dashboard has three primary
                features that set it apart from other tools in the field of
                astronomy. The first is a live dashboard that provides
                up-to-the-minute information on current events and trends. The
                second is an events search page that allows you to find specific
                events based on a variety of criteria such as: All messages in
                which some celestial body is involved in a time frame. All
                messages, or messages of a certain type, in a time frame. All
                messages originating from a certain observatory/telescope in a
                time frame. Finally, our analyze page uses machine learning to
                identify event patterns and sun preferences, helping you make
                more informed decisions about future observations. Whether
                you're an amateur astronomer or a seasoned professional, our
                dashboard is designed to help you stay on top of the latest
                developments in the field. By reflecting the relationships
                between different parameters in astronomy, we provide a
                comprehensive view of the cosmos that can help you make sense of
                the mysteries of the universe. So why wait? Enter to our
                dashboard today and start exploring the wonders of the cosmos
                like never before!
              </Typography>
              <Typography variant="h6" sx={{ py: 6, color: "#fff" }}>
                Version 1.0.0
              </Typography>
              <Typography variant="subtitle2" sx={{ color: "#fff" }}>
                COPYRIGHTS &copy;
              </Typography>
            </Container>
          </Grid>
        </Grid>
        <Box
          sx={{
            position: "absolute",
            top: 0,
            left: 0,
            backgroundColor: "rgba(0, 0, 0, 0.5)",
          }}
        />
      </Box>
    </Page>
  );
};

export default About;
